name: mighty_news
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Basic
  nb_utils: ^5.0.6
  google_fonts: ^4.0.3
  flutter_vector_icons: ^2.0.0

  #UI
  fading_edge_scrollview: ^3.0.0
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  story_view: ^0.14.0
  rive: ^0.9.1
  clippy_flutter: 2.0.0-nullsafety.1
  video_player: ^2.6.0

  #Network
  http: ^0.13.5
  intl: ^0.17.0-nullsafety.2
  html: ^0.15.2
  flutter_html: ^2.2.1
  webview_flutter: ^2.8.0

  #State
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  package_info: ^2.0.2

  #One Signal
  onesignal_flutter: ^3.5.1

  #Firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_remote_config: ^3.0.15
  firebase_crashlytics: ^3.0.17

  #AdMob
  google_mobile_ads: ^2.3.0
  facebook_audience_network: ^1.0.1

  #Social Login
  google_sign_in: ^6.0.2
  otp_text_field: ^1.1.3
  country_code_picker: ^3.0.0
  the_apple_sign_in: ^1.1.1

  #Other
  cached_network_image: ^3.2.3
  geolocator: ^9.0.2
  flutter_tts: ^3.6.3
  image_picker: ^0.8.7
  share: ^2.0.4
  url_launcher: ^6.1.10

  flutter_svg : ^0.22.0
  connectivity_plus: ^3.0.3
  dbus: ^0.7.8
  ffi: ^2.0.1
  xml: ^6.2.2

  flutter_localizations:
    sdk: flutter

dependency_overrides:
  xml: ^6.2.2
  modal_bottom_sheet: ^3.0.0-pre


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/
    - assets/rive/
